# Splunk HTTP Event Collector Configuration for Caldera
# This file is mounted to /opt/splunk/etc/apps/caldera_hec/local/inputs.conf

[http]
disabled = 0
port = 8088
enableSSL = 1
useDeploymentServer = 0

[http://caldera]
token = ${SPLUNK_HEC_TOKEN}
disabled = 0
index = threathunt
sourcetype = _json
source = caldera